simphony/osp-core

README.md
=> Updated old GitLab links

osp/core/ontology/docs/city.ontology.yml, osp/core/ontology/namespace.py, tests/test_api_city.py, tests/test_registry_city.py, tests/test_sqlite_city.py, tests/test_transport_session.py, tests/test_transport_sqlite_city.py, tests/test_utils.py
=> No inverse relationship crashes transport layer

osp/core/ontology/namespace_registry.py, osp/core/ontology/parser.py, tests/parser_test.yml, tests/test_namespace.py, tests/test_parser.py
=> Proper warning or error when calling from_iri with namespace not defined in yml

osp/core/__init__.py, osp/core/ontology/namespace_registry.py, osp/wrappers/simdummy/simdummy_session.py, packageinfo.py, tests/performance_test.py, tests/sqlite_performance_test.py, tests/test_api_city.py, tests/test_dataspace_wrapper.py, tests/test_filetransfer.py, tests/test_ontology_entity.py, tests/test_registry_city.py, tests/test_session_city.py, tests/test_sim_wrapper_city.py, tests/test_sqlite_city.py, tests/test_transport_auth.py, tests/test_transport_session.py, tests/test_transport_sim_wrapper.py, tests/test_transport_sqlite_city.py, tests/test_utils.py, tox.ini
=> Bring back support for pyhon v3.6

osp/core/ontology/namespace.py, tests/test_namespace.py
=> Make namespaces iterable: Iterate over entities.

osp/core/ontology/namespace.py, osp/core/ontology/parser.py, osp/core/tools/ontology2dot.py, tests/test_parser.py
=> Fix ontology2dot

osp/core/tools/yaml2camelcase.py
=> Comments on yaml2camelcase

osp/core/utils/general.py, tests/test_utils.py
=> Add easy way to serialize CUDS objects

osp/core/utils/general.py
=> Error importing validate_tree_against_schema

osp/core/ontology/attribute.py, osp/core/ontology/entity.py, osp/core/ontology/namespace.py, osp/core/ontology/namespace_registry.py, osp/core/ontology/oclass.py, osp/core/ontology/relationship.py, tests/sqlite_performance_test.py
=> removed license text

osp/core/ontology/yml/yml_parser.py, osp/core/ontology/yml/yml_validator.py, tests/default_rel_across_namespace_two_definitions.yml, tests/default_rel_across_namespace_uninstalled_entity.yml, tests/default_rel_across_namespace_uninstalled_namespace.yml, tests/default_rel_across_namespace_valid.yml, tests/test_namespace.py, tests/test_yml_parser.py
=> default relationship can now refer to different namespace

osp/core/ontology/installation.py, osp/core/pico.py
=> introduces keyword all. made error message a bit clearer

osp/core/__init__.py, osp/core/namespaces.py
All the user to specify the install directory of ontologies in an environment variable: $OSP_ONTOLOGIES_DIR
=> Allow to set install dir via env variable

osp/core/ontology/installation.py, osp/core/ontology/yml/yml_parser.py, tests/test_installation.py, tests/test_yml_parser.py
Same as https://github.com/simphony/osp-core/pull/530 but merge to dev
=> Reference OWL entity from YAML ontology Fixes #529 

osp/core/session/db/sql_wrapper_session.py, packageinfo.py
* Fixed clear database method
* packageinfo version up
=> Sql fixes (#545)

osp/core/ontology/parser.py, tests/test_parser.py
=> Fix issue 560 "format of ontology is not stored properly"

osp/core/ontology/docs/parser_test.ontology.yml, osp/core/ontology/yml/yml_parser.py
Just a little additional check was missing.
=> 575 Misinterpreting default_rel: false in YAML ontology

examples/api_example.py
As a side effect of pull request [#102](https://github.com/simphony/docs/pull/102) in the docs repository, this example needs to be updated.
=> Updated api example, as the tutorial on the CUDS API was also updated.

examples/ontology_example.py
As a side effect of pull request #107 in the docs repository, this example needs to be updated.
=> Updated ontology example, as the tutorial on the ontology interface was also updated.

osp/core/ontology/namespace.py
Fixes a bug that made it impossible to fetch the inverse of a relationship using the namespace.INVERSE_OF_hasRelationship notation when the reference by label keyword was enabled for the namespace. 
This regression was introduced in PR #584. Just noticed it now while solving another problem.
=> Fix regression: unable to fetch the inverse of a relationship using the namespace.INVERSE_OF_ syntax.

osp/core/utils/__init__.py
Add `'sparql'` to `__all__` in `osp.core.utils`.
=> Add `sparql` from utils to API Reference

osp/core/session/db/triplestore_wrapper_session.py, osp/core/session/transport/transport_utils.py
* Improve performance of applying the buffers for some wrappers (e.g. Allegrograph) adding all the triples at once.
* Simplify code of `osp.core.session.transport.transport_utils.import_rdf`.
=> Buffer performance improvements

osp/core/cuds.py, osp/core/utils/wrapper_development.py, tests/test_api_city.py
=> 662 Strange behaviour of CUDS remove (DataspaceSession)

osp/core/session/transport/transport_utils.py, tests/test_filetransfer.py
=> 652 cuba.file in dataspace session shows wrong file path on second load

packageinfo.py
Bump package version to 3.5.4.
=> Bump version to 3.5.4

Dockerfile, setup.py, tox.ini
* Docker image now builds (failing previously).
* Changed deprecated `MAINTAINER` to `LABEL org.opencontainers.image.authors`.
* Do not run tox when building the docker image, as GitHub's CI is already testing every commit.
=> Fix Dockerfile (`dev`)

osp/core/ontology/namespace.py, osp/core/ontology/namespace_registry.py, osp/core/ontology/ontology.py
=> 749 Error when installing ontologies with label languages both defined and undefined, and with duplicate label definitions

osp/core/session/session.py, osp/core/session/transport/transport_utils.py, osp/core/utils/general.py
=> Stop assigning an UID to imported CUDS with custom IRIs

osp/core/session/session.py, osp/core/session/transport/transport_utils.py, osp/core/utils/general.py
Analogous to #759.
Since it was already reviewed in #759 and this PR is just cherry-picking changes to a branch that somebody is using but that will be overwritten by `636-Redefining_containers`, I am merging this PR skipping the review procedure.
=>  Stop assigning an UID to imported CUDS with custom IRIs (`release/4/dev`)
