simphony/osp-core

osp/core/tools/yaml2camelcase.py
Previously the backup file `<>.yml.orig` was overwritten, when you called yaml2camelcase twice on the same file.
After these changes yaml2camelcase checks if the `<>.yml.orig` file exists. And if it does the backup is stored in a `<>.yml.orig[i]`
file, where i is increased from 0 until no file is overwritten
=> avoid overwriting backup file in yaml2camelcase

.github/CODEOWNERS
As per Issue #514 created a CODEOWNERS files.
Previously created a pull request for master branch PR #537 that needs to be discarded and closed without merging. 
This PR offer following changes:
1. Pull request for file CODEOWNERS changed from master to v3.5.0-dev branch.
2. Moving the CODEOWNERS file to .github/ folder as per the discussion in PR #537.
=> Codeowners in the dev branch

.github/workflows/ci.yml
The test B322 was designed for Python 2 and Bandit dropped support for it, therefore it no longer exists. See Bandit issue https://github.com/PyCQA/bandit/pull/662. Fixed by removing the explicit exclusion of this test when launching Bandit.
=> 580 Continuous integration fix

osp/core/ontology/namespace_registry.py, osp/core/ontology/oclass.py, tests/test_ontology_entity.py
There was a crash that was cause by an ontology not having a prefLabel for an entity. This should fix it. Tests pending.
=> Fix crash label missing

osp/core/cuds.py, osp/core/session/session.py, tests/test_api_city.py, tests/test_session_city.py, tests/test_transport_session.py, tests/test_utils.py
This will change the default session in a `with` statement:
```
with SomeWrapperSession() as session:
```
- I guess this makes the requirement that all wrapper object must be instantiated with an explicitly provided session obsolete
- This will sometimes break behavior as you can see from the tests. I hope this happens only in artificial cases like the tests
=> Allow to change default session with with

tests/test_filetransfer.py
This caused an error when building an OSP-core docker image
=> fixed unittest filetransfer

osp/core/ontology/parser.py
Fixes a bug that makes OSP-core fail before raising the actual intended exception when duplicate labels are found during the installation of an ontology (see linked issue).
=> 607 _check_duplicate_labels in ontology parser raises Keyerror

osp/core/ontology/namespace.py
Fix regression in `_get` method from `OntologyNamespace`. `_reference_by_label is False` was not being taken into account to choose to get the entity from its suffix.
Regression introduced in [6d1e341](https://github.com/simphony/osp-core/commit/6d1e341d68ed39ee81684013552ca49c77ba4055).
=> Fix regression in `_get` method from OntologyNamespace

osp/core/ontology/namespace.py, tests/test_namespace.py
This pull request aims to solve issue #591, at least for IPython users. The idea is to modify the `__dir__` method of namespaces to include their ontology entities, so that auto completion is offered. A similar thing could maybe be done for the `namespaces.py` files, I still have to do more research on this.
To Do list to complete the pull request
=> Add autocompletion for namespaces (IPython only)

osp/core/ontology/installation.py, osp/core/ontology/namespace_registry.py, osp/core/ontology/parser/yml/parser.py
The error was introduced in #658. When parsing the ontologies the validity of classes, is checked, but in some of the functions I forgot to use a ReadOnlyGraphAggregate to mix the graph of the namespace registry with the graph of the ontology, so for some ontologies the parsing was failing. This should fix the error. Closes #670.
=> 670 Error when installing ontologies

osp/core/ontology/datatypes.py, setup.py
* Support xsd:double RDF datatype.
* Enforce rdflib >= 5.0.0.
=> xsd:double support, enforce rdflib >= 5.0.0.

osp/core/ontology/docs/foaf.yml, tests/test_installation.py
Since it is no longer available at http://xmlns.com/foaf/spec/index.rdf, get it from https://web.archive.org/web/20210829023239/http://xmlns.com/foaf/spec/index.rdf.
If it ever goes back online, we can simply restore the original URL.
=> Get FOAF ontology from web archive

packageinfo.py, setup.cfg, setup.py
- Force `rdflib-jsonld == 0.6.1` for `python_version < '3.7'`.
- Force `websockets < 10`.
- Bump OSP-core version.
=> Force `rdflib-jsonld==0.6.1` for `python_version < '3.7'`. Force `websockets < 10`

Dockerfile, setup.py, tox.ini
* Docker image now builds (failing previously).
* Changed deprecated `MAINTAINER` to `LABEL org.opencontainers.image.authors`.
* Do not run tox when building the docker image, as GitHub's CI is already testing every commit.
----
Original PR is #723 (merge of hotfix to `dev`). This PR is the merge of the same hotfix branch to `master`.
=> Fix Dockerfile (`master`)

setup.py, tests/test_communication_engine.py
Closes #740 (Transport session not working with Python 3.10).
=> Require `websockets >= 10` for `python_version >= '3.10'` (dev)

setup.py, tests/test_communication_engine.py
Closes #740 (Transport session not working with Python 3.10).
=> Require `websockets >= 10` for `python_version >= '3.10'` (master)

osp/core/session/transport/communication_engine.py
=> Set the default ping_timeout for the websockets socket spawned by the `CommunicationEngineClient` to `None`.

packageinfo.py
Bump minor package version due to PR [#748](https://github.com/simphony/osp-core/pull/748). Old code works with the new version, but new code will not work with an old version in general (code turning the warning off).
=> Bump package version to 3.7.0

osp/core/session/db/triplestore_wrapper_session.py, osp/core/utils/general.py
"Vectorize" several methods of the class `TripleStoreWrapperSession` so that `_load_first_level` improves its performance.
=> Improve performance of `_load_first_level` for remote triplestores

osp/core/ontology/entity.py, osp/core/ontology/namespace.py, osp/core/ontology/namespace_registry.py, tests/test_namespace.py
Simple fix to the performance problem explained below.
--------
Consider the following code snippets, labeled as _slow code_ and _fast code_.
**Slow code**
```python
from osp.core.namespaces import mechanical as mt
from osp.core.namespaces import math, metrology
from osp.core.namespaces import properties as prop
from time import time
from tqdm import tqdm
n = (333636 // 3)
start = time()
for i in tqdm(range(0, n)):
bending_stiffness_average_value = 0.0312  # some numerical value
cableSystem = mt.CableBundle()
bendingStiffness_average = mt.BendingStiffness()
realNumber = math.Real(hasNumericalData=bending_stiffness_average_value)
bendingStiffness_average.add(realNumber, rel=metrology.hasQuantityValue)
cableSystem.add(bendingStiffness_average, rel=prop.hasProperty)
end = time()
print("time …
```
=> Cache access to namespace elements to improve performance
